# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🏗️ Build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      app_folder:
        type: string
        required: true
      repo:
        required: true
        type: string
      conan_version:
        required: true
        type: string

jobs:
  find_directory:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ inputs.repo }}
      - id: check_directory
        continue-on-error: true
        run: ls ${{ inputs.app_folder }}
    outputs:
      found: ${{ steps.check_directory.outcome }}

  build:
    needs: find_directory
    if: needs.find_directory.outputs.found == 'success'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ inputs.repo }}

      - name: 📥 Install CMake + Conan
        run: pip3 install cmake conan==${{ inputs.conan_version }}

      - name: 📡 Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
             https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 📡 Create and setup default profile
        run: conan profile detect --force

      - name: 👁️‍🗨️ Show conan profile
        run: conan profile show

      - name: 📦 Generate Package & Install Library (if possible)
        continue-on-error: true
        run: conan create . --build=missing -s compiler.version=11 -s compiler.cppstd=20 -s compiler=gcc -s compiler.libcxx=libstdc++ -s:b compiler.cppstd=20 -s:b compiler=gcc -s:b compiler.version=11 -s:b compiler.libcxx=libstdc++ -c tools.build:skip_test=True

      - name: 🏗️ Build
        working-directory: ${{ inputs.app_folder }}
        run: conan build . --build=missing -s:h compiler.version=11 -s:h compiler.cppstd=20 -s:h compiler=gcc -s:h compiler.libcxx=libstdc++
