# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 🧪 tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      library:
        required: true
        type: string
      coverage:
        required: true
        type: boolean
      fail_on_coverage:
        required: true
        type: boolean
      coverage_threshold:
        required: true
        type: string
      repo:
        required: true
        type: string
      conan_version:
        required: true
        type: string

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolchain: gcc
            compiler_version: 12
            os: ubuntu-22.04
            standard_library: libstdc++
            installations:
            enable_coverage: ${{ inputs.coverage }}
            profile_path: profiles/x86_64/linux/

          - toolchain: apple-clang
            compiler_version: 14
            os: macos-12
            standard_library: libc++
            installations:
            profile_path: profiles/x86_64/mac/

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          repository: ${{ inputs.repo }}

      - name: 📥 Install OS Specific Tools
        if: ${{ matrix.installations != '' }}
        run: ${{ matrix.installations }}

      - name: 📥 Install CMake + Conan
        run: pip3 install cmake conan==${{ inputs.conan_version }}

      - name: 📡 Add `libhal-trunk` conan remote
        run: conan remote add libhal-trunk
          https://libhal.jfrog.io/artifactory/api/conan/trunk-conan

      - name: 📡 Create and setup default profile
        run: conan profile detect --force

      - name: 👁️‍🗨️ Show conan profile
        run: conan profile show

      - name: 📡 Install default profiles
        run: conan config install -sf ${{ matrix.profile_path }} -tf profiles https://github.com/libhal/conan-config.git

      - name: 🔬 Create & Run Unit Tests
        run: conan create . --build=missing -s compiler.cppstd=20 -s compiler.version=${{ matrix.compiler_version }} -s compiler.libcxx=${{ matrix.standard_library }} -s compiler=${{ matrix.toolchain }} -s build_type=Debug

      - name: 🔬 Build & Run Unit Tests
        run: conan build . --build=missing -s compiler.cppstd=20 -s compiler.version=${{ matrix.compiler_version }} -s compiler.libcxx=${{ matrix.standard_library }} -s compiler=${{ matrix.toolchain }} -s build_type=Debug

      - name: 📥 Install GCovr
        if: ${{ matrix.enable_coverage }}
        run: pip3 install gcovr

      - name: 🔎 Generate Code Coverage
        if: ${{ matrix.enable_coverage }}
        working-directory: build
        run: |
          mkdir coverage/ && python3 -m gcovr --root ../../ --exclude ".*/third_party/.*" --cobertura coverage/coverage.xml --html coverage/index.html --html-details --sort-percentage

      - name: Coverage Summary
        if: ${{ matrix.enable_coverage }}
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/coverage.xml
          badge: true
          fail_below_min: ${{ inputs.fail_on_coverage }}
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: ${{ inputs.coverage_threshold }}

      - name: Extract & Save Coverage SVG
        if: ${{ matrix.enable_coverage }}
        run: wget
          $(cat code-coverage-results.md |
          grep -Eo 'https://img.shields.io/badge/[^)]*')
          -O build/coverage/coverage.svg

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.enable_coverage }}
        with:
          name: coverage
          retention-days: 1
          path: build/coverage/

      - name: 📡 Sign into JFrog Artifactory
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          API_KEY: ${{ secrets.JFROG_LIBHAL_TRUNK_API_KEY }}
          JFROG_USER: ${{ secrets.JFROG_LIBHAL_TRUNK_USER }}
        run: conan remote login -p $API_KEY libhal-trunk $JFROG_USER

      - name: 🆙 Upload package to `libhal-trunk` repo
        if: ${{ github.ref == 'refs/heads/main' }}
        run: conan upload "${{ inputs.library }}/*" --confirm -r=libhal-trunk
